services:
  api:
    image: prospectbdapprovaldesk-api:latest
    build:
      context: .
      dockerfile: src/ProspectbdApprovalDesk.Api/Dockerfile
    container_name: prospectbdapprovaldesk-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ProspectbdApprovalDeskDb;Username=postgres;Password=postgres

    networks:
      - traefik-network

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.approval-desk-backend.rule=Host(`approval-desk.prospectbdltd.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.approval-desk-backend.entrypoints=web"
      - "traefik.http.services.approval-desk-backend.loadbalancer.server.port=8080"
  approval-desk-frontend:
    image: prospectbdapprovaldesk-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:5096
    container_name: prospectbdapprovaldesk-frontend

    networks:
      - traefik-network

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.approval-desk-frontend.rule=Host(`approval-desk.prospectbdltd.com`)"
      - "traefik.http.routers.approval-desk-frontend.entrypoints=web"
      - "traefik.http.services.approval-desk-frontend.loadbalancer.server.port=80"

volumes:
  prospectbdapprovaldesk_pgdata:
networks:
  traefik-network:
    external: true
